spring:
  thymeleaf:
    cache: false
  datasource:
    db-fwzx:
      jdbc-url: jdbc:oracle:thin:@172.16.192.139:1521/BJ.NET
      username: tyyw
      password: tyyw
      driver-class-name: oracle.jdbc.OracleDriver

