spring:
  thymeleaf:
    cache: false
  datasource:
    name: dataSource
    url: jdbc:ArteryBase://172.16.34.123:5432/testwjf?currentSchema=public
    username: sa
    password: ENCRYPT#g3J0wPwVx24eVe/lEupktA==
    driver-class-name: com.thunisoft.ArteryBase.Driver
artery:
  schema: db_aty
