spring:
  thymeleaf:
    cache: false
  datasource:
    name: dataSource
    url: jdbc:ArteryBase://172.16.193.220:5432/db_orchid
    username: sa
    password: ENCRYPT#g3J0wPwVx24eVe/lEupktA==
    driver-class-name: com.thunisoft.ArteryBase.Driver
artery:
  login:
    enabled: true
